#####################################################################
# Copyright (C) 2025 ETH Zürich (ethz.ch)
# Chair of Information Management (im.ethz.ch; github.com/im-ethz)
# Bosch Lab at University of St. Gallen and ETH Zürich (iot-lab.ch)
#
# Authors: Robin Deuber, Kevin Koch, Patrick Langer, Martin Maritsch
#
# Licensed under the MIT License (the "License");
# you may only use this file in compliance with the License.
# You may obtain a copy of the License at
#
#         https://mit-license.org/
#
# THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
# OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
# WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#####################################################################

alcohol_subjects: [201, 203, 205, 208, 212, 213, 214, 215, 218, 219, 220, 223,
                   224, 227, 228, 229, 230, 232, 233, 238, 240, 241, 245, 247,
                   250, 254, 259, 260, 262, 265, 273]

reference_placebo_subjects: [207, 217, 234, 235, 236, 243, 249, 264, 267, 268,
                             270, 202, 209, 211, 221, 237, 239, 244, 256, 257,
                             258, 266, 242]

n_jobs: 19
frequency: 50
data_directory: '/test_track'
data_output_directory: '/test_track_processed'
reference_phase_set_to: 1
set_reference_phase: False
reusing_old_df: True
