#####################################################################
# Copyright (C) 2025 ETH Zürich (ethz.ch)
# Chair of Information Management (im.ethz.ch; github.com/im-ethz)
# Bosch Lab at University of St. Gallen and ETH Zürich (iot-lab.ch)
#
# Authors: Robin Deuber, Kevin Koch, Patrick Langer, Martin Maritsch
#
# Licensed under the MIT License (the "License");
# you may only use this file in compliance with the License.
# You may obtain a copy of the License at
#
#         https://mit-license.org/
#
# THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
# OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
# WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#####################################################################

# Define which probands should be considered
probands_selected: ['201', '202', '203', '205', '207', '208', '209', '211', '212', '213',
                    '214', '215', '217', '218', '219', '220', '221', '223', '224', '227',
                    '228', '229', '230', '232', '233', '234', '235', '236', '237', '238',
                    '239', '240', '241', '242', '243', '244', '245', '247', '249', '250',
                    '254', '256', '257', '258', '259', '260', '262', '264', '265', '266',
                    '267', '268', '270', '273']

# Define directories
data_directory_processed: '/test_track_processed'

# Use multiple cores when aggregating participants
multi_cores: False

# Recalculate even if merged files already exist
enforce_recalculation: True

# Phases and scenarios to retain
selected_phases: [1, 2, 3]
selected_scenarios: ['highway', 'rural', 'city']

# Binary features required for interpolation
binary_features: ['eye+right_eye_state+', 'eye+left_eye_state+',
                  'aoi+driver_side_windscreen+', 'aoi+copilot_side_windscreen+',
                  'aoi+left_rear_mirror+', 'aoi+right_rear_mirror+',
                  'aoi+left_window+', 'aoi+right_window+',
                  'aoi+central_rear_mirror+', 'aoi+driver_instruments+',
                  'aoi+navigation_display+', 'aoi+middle_instrument_cluster+',
                  'event+FIXA+onehot', 'event+SACC+onehot']
